### ISSUE TITLE
HTTP(s)

### ISSUE THREAD

**Issue by kopax** [JensErat/docker-seafile#11]
Does this work with HTTPS ?

Can we use a relative path like `/seafile` ?

it would be nice to add a docker-compose.yml to customize this installation.

**Comment by JensErat** [comment]
For adding HTTPs, you'll have to put a reverse proxy in front of Seafile (you'd have to do so anyway). The Seafile documentation already has information on required settings. I'm successcully using nginx. As you can change all configuration, you can use arbitrary paths as documented by Seafile.

A docker-compose.yml will be added as soon as the Dockerfile is split up into two containers (Seafile backend and seahub). I will add some information on how to migrate (and have the old one stay around), it's time to move away from the phusion baseimage and tune some parts to be more Docker-compliant.

**Comment by ypid** [comment]
I also use Ngnix as reverse proxy and TLS termination. I have some of this configuration on GitHub if you are interested: https://github.com/ypid/docker-makefile/blob/850c6e04d72bacba746b13b525c714b0bb7af13a/Makefile#L269-L287
https://github.com/ypid/docker-gen/blob/ypid-template/templates/nginx-ssl-include.tmpl
This allows me to run more than one Seafile instance.
