### ISSUE TITLE
wrong github description + wrong docker hub readme

### ISSUE THREAD

**Issue by superzazu** [JensErat/docker-seafile#18]
Hello,

The github description says " Dockerfile for a Seafile **3** image" and the Docker HUB description says "Seafile **4** for Docker". I'd be neat to update these two descriptions as they are misleading.

Best regards

**Comment by JensErat** [comment]
Thank you for pointing this out.

- I updated the Github short description.
- I triggered another build on the Docker Hub, I'm not sure why the Hub missed out the changed REAME.md from Github.
