### ISSUE TITLE
Run the garbage collector periodically

### ISSUE THREAD

**Issue by Crafter6432** [JensErat/docker-seafile#20]
It would be nice if the image had an option to run the GC periodically in order to reduce seafile's storage requirements.

**Comment by viktorlindgren** [comment]
How should possible errors be handled then?

This is my cleanup script that I run each saturday
`
#!/bin/bash
cd ~/haiwen/seafile-server-latest

./seahub.sh stop
sleep 5
./seafile.sh stop
sleep 5;

cd seafile
export LD_LIBRARY_PATH=./lib:${LD_LIBRARY_PATH}

cd ..
./seaf-gc.sh
./seaf-gc.sh -r

cd ~/haiwen/seafile-server-latest
./seafile.sh start
./seahub.sh start-fastcgi
`

[cleanup.txt](https://github.com/JensErat/docker-seafile/files/391790/cleanup.txt)

**Comment by Pimmetje** [comment]
For me a command we can run from docker would be enough. `docker exec -it seafile /opt/seafile/cleanup.sh`
This way u can run it as a cron or manually very easy

**Comment by JensErat** [comment]
Closing this for now, as it does not really discuss requirements on the Docker image/Dockerfile, but is more about application orchestration (pull requests for `docker-compose.yml` files for Docker compose/Docker swarm mode or Kubernetes pod descriptions are welcome, though).
