### ISSUE TITLE
Work with jwilder/nginx-proxy ?

### ISSUE THREAD

**Issue by clementvp** [JensErat/docker-seafile#23]
I follow every steps, but i can't get this work fine with [a nginx proxy](https://github.com/jwilder/nginx-proxy)
After the second boot of the container if i go to my sub domain, like seafile.example.com OR example.com, i get nothing.
Nothing either with these flags : -e fatcgi=true -e VIRTUAL_HOST=seafile.example.com

Beside, if i install this on a fresh machine (without proxy) i get nothing to my main domain.
I know this is just a wrap up of seafile, but anyone to show my how to set up this with jwilder nginx proxy ?

**Comment by JensErat** [comment]
I'm sorry, I don't know that project. You will have to dig through the web proxy's logs to get an understanding what's going wrong -- no matter whether it is a proxy or Seafile issue, but that would be the starting point.
