### ISSUE TITLE
symlink probably not added

### ISSUE THREAD

**Issue by mancvso** [JensErat/docker-seafile#9]
Hi!
The startup scripts (those that run when autostart=true) are referencing
`/opt/seafile/seafile-server-latest` but the symbolic link is never created, thus the services are never executed on boot.
I've had to do that manually with
`ln -s /opt/seafile/seafile-server-4.0.5 /opt/seafile/seafile-server-latest`
Am I missing something?

**Comment by JensErat** [comment]
Seafile is not ready yet for "automatic upgrades", thus all the setup stuff has to be done manually yet. Did you run the setup? This should add the link without manual internvention.

I already had some thoughts on automating the database upgrades, and will integrate the current seafile version in the image (so no downloader any more, maybe even split up the image in multiple ones to be really "Docker-compliant"). Will takes some more weeks as Seafile isn't an easy service to cleanly put into Docker's paradigms, but this will happen. Definitely.

**Comment by mancvso** [comment]
Ahm... I've switched versions without a single issue (3.0.4 -> 3.1.6 -> 4.0.5). But you are right; a layered history (tags) is more "Dockerish" approach.

**Comment by JensErat** [comment]
So the issue is resolved for now? I closed the issue, if you've still got problems just reply again.

**Comment by mancvso** [comment]
Still needed to use the symlink when upgrading.

**Comment by JensErat** [comment]
I will look into cleaning up the Dockerfile soon, need to upgrade my own setup anyway. I guess until then symlinking manually should be fine.
